recipe: default.v1
language: es
pipeline:
- name: SpacyNLP
  model: es_core_news_sm
  case_sensitive: false
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: word
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 2
  max_ngram: 4
- name: DIETClassifier
  entity_recognition: false
  epochs: 200
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 200
policies:
- name: MemoizationPolicy
  max_history: 5
  epochs: 150
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
assistant_id: 20230427-102245-silent-toast
